### ISSUE TITLE
Error when using "Go install"

### ISSUE THREAD

**Issue by pranayjoshi** [cybertec-postgresql/pgwatch3#381]
**Describe the bug**
When using the command `go install ` the terminal throw an error `go: download go1.22 for darwin/arm64: toolchain not available`

**To Reproduce**
1. Go to './src'
3. open terminal and type `go install`

**Expected behavior**
No error returned

**Screenshots**
<img width="574" alt="Screenshot 2024-03-02 at 1 28 21 AM" src="https://github.com/cybertec-postgresql/pgwatch3/assets/35572191/bc0f2866-3531-4fe3-b0b9-1ad9f0284e2b">

**Desktop (please complete the following information):**
 - OS: Mac OS[e.g. iOS]

**Smartphone (please complete the following information):**

**My View**
Personally I think that as the project is using Docker, this issue shouldn't be a major problem, because I tried it setting up myself using docker-compose. But, the main issue lies with the `go version` using `go 1.21` instead of `go 1.22` solves this issue.

**Comment by pashagolub** [comment]
You need to download and install go1.22 for darwin/arm64! Because toolchain is not available on your machine. https://github.com/golang/go/issues/65568
