### ISSUE TITLE
panic at `pgwatch3/log/log_broker_hook.go`

### ISSUE THREAD

**Issue by qazxcdswe123** [cybertec-postgresql/pgwatch3#387]
**Describe the bug**
pgwatch3 die after a few minutes of idle
 

**Steps to produce the behavior:**
1. Follow the readme to add test db and bench
2. poke around the webui and wait for a while?
3. panic

~~I haven't been able to reproduce it though~~ reproduced (but the situation is kinda like iterator's use after invalidation)

**Screenshots**
~~I wonder if its also related to the sql error above~~
Not related but weird
<img width="956" alt="image" src="https://github.com/cybertec-postgresql/pgwatch3/assets/29861494/b9af3d9f-9abb-4782-898b-7331ac21bd52">

```
panic: runtime error: index out of range [1] with length 1

goroutine 902 [running]:
github.com/cybertec-postgresql/pgwatch3/log.(*BrokerHook).RemoveSubscriber(0xc0000a7110, 0xc000618420)
	/pgwatch3/log/log_broker_hook.go:59 +0x205
github.com/cybertec-postgresql/pgwatch3/webserver.writer(0xc0000b3080, {0x1638860, 0xc00003ebd0})
	/pgwatch3/webserver/wslog.go:64 +0x2a2
created by github.com/cybertec-postgresql/pgwatch3/webserver.(*WebUIServer).serveWsLog in goroutine 915
	/pgwatch3/webserver/wslog.go:82 +0x1ba
```

Fix: iterate from back to front so you don't have to worry about indexes that are deleted

**Comment by pashagolub** [comment]
Thanks. Is it reproducible against `master`?

**Comment by qazxcdswe123** [comment]
> Thanks. Is it reproducible against master?

I used the `docker-compose` file and it builds the image from source. So yes I think so

**Comment by qazxcdswe123** [comment]
@pranayjoshi 
No, here is my output, and I've tested that it works on both mac and linux

```
Attaching to add-test-db-1
add-test-db-1  | BEGIN
add-test-db-1  | CREATE EXTENSION
add-test-db-1  | CREATE FUNCTION
add-test-db-1  | psql:/tmp/00_helpers/get_table_bloat_approx/9.5/metric.sql:47: NOTICE:  ALTER FUNCTION get_table_bloat_approx() SET search_path TO public
add-test-db-1  | DO
add-test-db-1  | COMMIT
add-test-db-1  | BEGIN
add-test-db-1  | CREATE FUNCTION
add-test-db-1  | GRANT
add-test-db-1  | COMMENT
add-test-db-1  | psql:/tmp/00_helpers/get_table_bloat_approx_sql/12/metric.sql:153: NOTICE:  ALTER FUNCTION get_table_bloat_approx_sql() SET search_path TO public
add-test-db-1  | DO
add-test-db-1  | COMMIT
add-test-db-1  | INSERT 0 1
add-test-db-1 exited with code 0
```

**Comment by Massinja** [comment]
@pranayjoshi unless you've aliased your "docker-compose" to "docker compose", you are running an older, deprecated Compose V1. That could be an issue. As it's running fine in my environment.

**Comment by pranayjoshi** [comment]
> @pranayjoshi unless you've aliased your "docker-compose" to "docker compose", you are running an older, deprecated Compose V1. That could be an issue. As it's running fine in my environment.

Here is the output to my docker compose version
`docker-compose --version
Docker Compose version v2.24.3-desktop.1`

**Comment by Massinja** [comment]
@pranayjoshi Looks good to me (and Docker Desktop provides an alias by default to a newer version). 
In such way,  what do you mean by this:
`Then I tried building the golang and webui by their respective commands.`

As this alone will start all the services:
`docker-compose up --detach`

Have you tried adding test database at http://localhost:8080/ instead of command line?

**Comment by pranayjoshi** [comment]
@Massinja 
`Then I tried building the golang and webui by their respective commands.` I just mean that I build the UI using yarn/npm. I don't think it has to do anything with the project itself.
`Have you tried adding test database at http://localhost:8080/ instead of command line?` no I haven't tried that. What are the steps to add the test database via UI?

**Comment by pranayjoshi** [comment]
Update: Cool I solved it by just recloning the repo 🤣
