### ISSUE TITLE
Values not set in StatsServerHandler

### ISSUE THREAD

**Issue by ondar** [cybertec-postgresql/pgwatch3#422]
**Describe the bug**
It seems that func StatsServerHandler in main.go always return 0 for databasesConfigured, databasesMonitored and unreachableDBs. is it even called from anywhere? I don't see it being added to any server mux?

**To Reproduce**
Observation from code. Or am I missing something?

**Expected behavior**
StatsServerHandler added to server mux so it can serve HTTP calls and return correct values.

**Comment by pashagolub** [comment]
It's broken. Will be fixed later

**Comment by ondar** [comment]
Thanks. Looking for using pgwatch3 in our organization and this looked to be not implemented yet.

I also found these small problems:
- In file src/db/sql/metric/README.md in row 2 file roll_out_*.psql is referenced, but I can't find it anywhere? Same with 00_schema_base.sql and 01_old_metrics_cleanup_procedures.sql.
- In file docs/ENV_VARIABLES.md you state that environment variable PW3_PG_SCHEMA_TYPE can contain values **metric-time** or **metric-dbname-time**, but in file docker/bootstrap/init_dbs.sh you test this variable only for value **timescale**?

Should I create separate bugs for these, or those are known problems? 😄

**Comment by pashagolub** [comment]
Oh! Fair enough! Those are doc issues and should be fixed. I'd you can create separate issues that would be great! Thanks for your help. 

PS. Pgwatch3 is in a dev cycle at the moment, so it better to try pgwatch2 in production meanwhile.

**Comment by ondar** [comment]
Thanks. Issues https://github.com/cybertec-postgresql/pgwatch3/issues/423 and https://github.com/cybertec-postgresql/pgwatch3/issues/424 created.

I know it is in dev cycle now - we are too, so I'm fine with that for now 😃. I want to use pgwatch3 (apart from Postgres monitoring) as a event store for Grafana. Is there a way to somehow provide timestamp of last event written to a metric for particular database - like give me all events newer than this timestamp? I was looking at how index change is implemented here, but that is not exactly what I need. I'm fine with developing this feature if you point me in right direction.
