### ISSUE TITLE
Unable to add new DB through UI

### ISSUE THREAD

**Issue by ondar** [cybertec-postgresql/pgwatch3#426]
**Describe the bug**
When adding new database monitoring through UI, error "ERROR: new row for relation "source" violates check constraint "source_dbtype_check" (SQLSTATE 23514)". When this constraint is removed from DB, adding fires another constraint as if backed tries to write all empty values to DB. Adding directly to DB works. This was working 3 months ago when I 1st tested it. Pressing "Test connection" report success.

**To Reproduce**
1. Build pgwatch3 from master branch with docker compose build pgwatch3
2. Run pgwatch3 with default docker compose file.
3. Go to UI, dashboard, click to "+ NEW" button, fill in the data, click "Start monitoring"
5. See red error in lower left corner.

**Expected behavior**
Adding new source through UI works.

**Screenshots**
![image](https://github.com/cybertec-postgresql/pgwatch3/assets/5563787/49af0728-29d3-4eed-84fc-857ea9cdfee3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Additional context**
Also tab "Presets" seems to be empty, but data seems to be going in:
![image](https://github.com/cybertec-postgresql/pgwatch3/assets/5563787/54df6b52-d5c8-48e2-a4e1-e45561f5cf86)
Also adding new metrics report success, but metrics is not added:
![image](https://github.com/cybertec-postgresql/pgwatch3/assets/5563787/a3be68f9-2d06-478d-a582-489e1712c83e)

**Comment by ondar** [comment]
Seems that editing database under monitoring is not working too - pressing edit button opens empty window (same as when you press "+ NEW" button).

**Comment by pashagolub** [comment]
this is why we have #403 and #421 opened. We are actively working on webui.

Please, consider it broken and use other ways to put sources under monitoring (either use YAMl config file or add directly to database with psql or other client).

Thanks for understanding!

**Comment by pashagolub** [comment]
After all bug fixes we will release it :)

**Comment by ondar** [comment]
And now there's dilemma - should we try to find more so its a better product but released later? 😁 Because so far it seems to be checking quite a few boxes on what we want to deploy here in our company.

Btw I tried to push new branch to your repo with a few small typo fixes, but got 403. It is error on my end, or only approved people can push?

**Comment by pashagolub** [comment]
>And now there's dilemma - should we try to find more so its a better product but released later?

It's up to you. At the moment webui is the thing we need to finish to go at least to beta. And I'm struggling to provide any time frame because I don't write front-end and thus dependent on my colleagues.

>Btw I tried to push new branch to your repo with a few small typo fixes, but got 403. It is error on my end, or only approved people can push?


People are allowed to create pull requests. Everything else is forbidden, of course. :)

**Comment by ondar** [comment]
I might be able to help. But how to create pull request if you can't push new branch first?

**Comment by ondar** [comment]
@pashagolub sorry I was out for a week, but if you want me to help with something throw some ticket at me. I never tried programming in GO but it seems it's not that hard looking at the code. I can try something simpler. But I can help with typescript stuff. I have some limited knowledge with that. My java programming skills won't help much here 😁
