### ISSUE TITLE
Error While adding new database to sources using WebUI

### ISSUE THREAD

**Issue by destrex271** [cybertec-postgresql/pgwatch3#471]
**Describe the bug**
Getting the following error while adding a new database thru the webui: 
ERROR: new row for relation "source" violates check constraint "source_dbtype_check" (SQLSTATE 23514) 

**To Reproduce**
1. Go to 'webui'
2. Add New Database and keep option 'postgres' in db type in main
3. Click on start monitoring

**Expected behavior**
Should create the row entry without any errors

**Screenshots**
![image](https://github.com/cybertec-postgresql/pgwatch3/assets/59926121/d05d1254-56ce-4391-bf08-f7b979bd7520)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox

**Comment by pashagolub** [comment]
fixed by #473
