### ISSUE TITLE
PGWatch3 does not respect source DB version for metric queries

### ISSUE THREAD

**Issue by krisavi** [cybertec-postgresql/pgwatch3#489]
**Describe the bug**
PGWatch3 does not seem to use PG13 queries and uses PG15 or PG16 queries for PG14 source.

**To Reproduce**
1. Add PG14 Source
2. Collect pg_stat_statements and table_stats
3. Check error log

**Expected behavior**
I expect no errors in log.

**Versions:**
pgwatch3:
  Version:      master
  DB Schema:    00179
  Git Commit:   742775e04f626792bf6906065f6c58bf68bb2e4a
  Built:        2024-07-23T17:27:23+02:00
postgres 
```
SELECT dbname, data->>'major_version' as major_version, data->>'server_version' as server_version, data->>'server_version_num' as server_version_num FROM settings LIMIT 1;
   dbname   | major_version | server_version | server_version_num
------------+---------------+----------------+--------------------
 Lab_zabbix | 14            | 14.12          | 140012
```

**Additional context**
Log entries since it uses PG 15 queries.
```
2024-07-24 09:56:42.933 [ERROR] [source:Lab_zabbix] [metric:stat_statements] [error:ERROR: column "temp_blk_read_time" does not exist (SQLSTATE 42703)] failed to fetch metric data
2024-07-24 09:56:42.962 [ERROR] [source:Lab_zabbix] [metric:table_stats] [error:ERROR: column "last_seq_scan" does not exist (SQLSTATE 42703)] failed to fetch metric data
```

**Comment by pashagolub** [comment]
Thanks! Looks like a bug!
